/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongkhamtu.receptionpatient.view.receptionist;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlyphongkhamtu.receptionpatient.dao.PatientDAO;
import quanlyphongkhamtu.receptionpatient.model.Patient;
import quanlyphongkhamtu.receptionpatient.model.User;

/**
 *
 * @author tminh
 */
public class SearchPatientFrm extends javax.swing.JFrame {

    private User user;
    private List<Patient> listPatient;
    
    /**
     * Creates new form PatientReceptionFrm
     */
    public SearchPatientFrm(User user) {
        this.user  = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSearchPatient = new javax.swing.JPanel();
        lblSearchPatient = new javax.swing.JLabel();
        lblUserFullName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        lblKey = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListPatient = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm kiếm bệnh nhân");
        setLocation(new java.awt.Point(100, 60));
        setLocationByPlatform(true);
        setResizable(false);

        pnSearchPatient.setPreferredSize(new java.awt.Dimension(1040, 640));

        lblSearchPatient.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblSearchPatient.setText("Tìm kiếm bệnh nhân");

        lblUserFullName.setText("Name");
        lblUserFullName.setText(user.getFullName());

        lblUsername.setText("Username");
        lblUsername.setText(user.getUsername());

        txtKey.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtKey.setMinimumSize(new java.awt.Dimension(12, 36));
        txtKey.setPreferredSize(new java.awt.Dimension(780, 36));
        txtKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeyActionPerformed(evt);
            }
        });

        lblKey.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblKey.setText("Tên bệnh nhân:");

        btnSearch.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.setPreferredSize(new java.awt.Dimension(79, 36));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblListPatient.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tblListPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Tên bệnh nhân", "Tuổi", "Địa chỉ", "CCCD", "SĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListPatient.setRowHeight(36);
        tblListPatient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblListPatientFocusGained(evt);
            }
        });
        tblListPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListPatient);

        btnBack.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.setPreferredSize(new java.awt.Dimension(100, 36));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSearchPatientLayout = new javax.swing.GroupLayout(pnSearchPatient);
        pnSearchPatient.setLayout(pnSearchPatientLayout);
        pnSearchPatientLayout.setHorizontalGroup(
            pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSearchPatientLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnSearchPatientLayout.createSequentialGroup()
                        .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKey))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnSearchPatientLayout.createSequentialGroup()
                                .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnSearchPatientLayout.createSequentialGroup()
                                .addComponent(lblSearchPatient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUserFullName, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(23, 23, 23))
        );
        pnSearchPatientLayout.setVerticalGroup(
            pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchPatientLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnSearchPatientLayout.createSequentialGroup()
                        .addComponent(lblUserFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername))
                    .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearchPatient)))
                .addGap(26, 26, 26)
                .addGroup(pnSearchPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKey)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnSearchPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeyActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        JButton btnClicked = (JButton)evt.getSource();
        if (btnClicked.equals(btnSearch)) {
            if ((txtKey.getText() == null) || (txtKey.getText().length() == 0))
                return;
            PatientDAO patientDAO = new PatientDAO();
            listPatient = new ArrayList<>(patientDAO.searchPatient(txtKey.getText().trim()));
            
            if (listPatient == null || listPatient.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy bệnh nhân!",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String[] columnNames = {"STT", "ID", "Tên bệnh nhân", "Tuổi", "Địa chỉ", "CCCD", "SĐT"};
                String[][] values = new String[listPatient.size()][7];
                for (int i = 0; i < listPatient.size(); i++) {
                    values[i][0] = String.valueOf(i + 1);
                    values[i][1] = String.valueOf(listPatient.get(i).getId());
                    values[i][2] = listPatient.get(i).getFullName();
                    values[i][3] = String.valueOf(listPatient.get(i).getAge());
                    values[i][4] = listPatient.get(i).getAddress();
                    values[i][5] = listPatient.get(i).getCitizenId();
                    values[i][6] = listPatient.get(i).getPhone();
                }
                DefaultTableModel tableModel = new DefaultTableModel(values, columnNames) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        // make cell be unable to edit
                        return false;
                    }
                };
                tblListPatient.setModel(tableModel);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblListPatientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblListPatientFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListPatientFocusGained

    private void tblListPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListPatientMouseClicked
        // TODO add your handling code here:
        // get the colume of the button
        int colume = tblListPatient.getColumnModel().getColumnIndexAtX(evt.getX());
        // get the row of the button
        int row = evt.getY() / tblListPatient.getRowHeight();
        
        // Checking the row or column is valid or not
        if (row < tblListPatient.getRowCount() && row >= 0
                && colume < tblListPatient.getColumnCount() && colume >= 0) {
            (new SearchActiveRoomFrm(user, listPatient.get(row))).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tblListPatientMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if ((evt.getSource() instanceof JButton) && (((JButton) evt.getSource()).equals(btnBack))) {
            (new PatientReceptionFrm(user)).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPatientFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblSearchPatient;
    private javax.swing.JLabel lblUserFullName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnSearchPatient;
    private javax.swing.JTable tblListPatient;
    private javax.swing.JTextField txtKey;
    // End of variables declaration//GEN-END:variables
}
